//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefDocTest
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblScope;
        protected global::System.Web.UI.WebControls.TextBox txtScope;
        protected global::System.Web.UI.WebControls.Button btnGetToken;
        protected global::System.Web.UI.WebControls.Button btnCallGraph;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtOutput;
    }
}