//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefDocTest
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkHome;
        protected global::System.Web.UI.WebControls.HyperLink lnkLogin;
        protected global::System.Web.UI.WebControls.HyperLink lnkLogout;
        protected global::System.Web.UI.WebControls.Label lblUser;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}